service: wayvote-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::www.wayvote.org/*"
        - Effect: Allow
          Action:
            - cloudfront:CreateInvalidation
          Resource: "*"

custom:

functions:
  api:
    handler: api.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

resources:
  Resources:
    # S3 bucket for static site hosting
    WayvoteWebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub 'wayvote-website-${self:provider.stage}'
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false


  Outputs:
    ApiGatewayRestApi:
      Value: !Ref ApiGatewayRestApi
      Export:
        Name: wayvote-api-${self:provider.stage}-ApiGatewayRestApi
    WayvoteWebsiteBucketName:
      Value: !Ref WayvoteWebsiteBucket
      Export:
        Name: wayvote-frontend-${self:provider.stage}-WebsiteBucketName
    ApiGatewayUrl:
      Value: !Sub 'https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${self:provider.stage}'
      Export:
        Name: wayvote-api-${self:provider.stage}-ApiGatewayUrl
